<?php

namespace Plugin\UKOMI4\Form\Type\Admin;

use Eccube\Entity\Master\OrderStatus;
use Eccube\Form\Type\Master\OrderStatusType;
use Plugin\UKOMI4\Entity\Config;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class ConfigType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('api_key', TextType::class, [
            'required' => true,
            'constraints' => [
                new NotBlank()
            ],
        ])->add('api_secret', TextType::class, [
            'required' => true,
            'constraints' => [
                new NotBlank()
            ]
        ])->add('order_status', OrderStatusType::class, [
            'expanded' => false,
            'multiple' => false,
            'placeholder' => '選択してください。'
        ])->add('no_auto', CheckboxType::class, array(
            'label' => '自動導入を無効にする',
            'required' => false,
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}
