<?php


namespace Plugin\UKOMI4\Form\Type\Admin;


use Doctrine\ORM\EntityManager;
use Eccube\Entity\Master\OrderStatus;
use Eccube\Form\Type\Master\OrderStatusType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SyncType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('sync_date_start', DateType::class, [
            'required' => true,
            'input' => 'datetime',
            'widget' => 'single_text',
            'format' => 'yyyy-MM-dd',
            'placeholder' => ['year' => '----', 'month' => '--', 'day' => '--'],
            'attr' => [
                'class' => 'datetimepicker-input',
                'data-target' => '#' . $this->getBlockPrefix() . '_sync_date_start',
                'data-toggle' => 'datetimepicker'
            ]
        ])->add('sync_date_end', DateType::class, [
            'required' => true,
            'input' => 'datetime',
            'widget' => 'single_text',
            'format' => 'yyyy-MM-dd',
            'placeholder' => ['year' => '----', 'month' => '--', 'day' => '--'],
            'attr' => [
                'class' => 'datetimepicker-input',
                'data-target' => '#' . $this->getBlockPrefix() . '_sync_date_end',
                'data-toggle' => 'datetimepicker'
            ]
        ])->add('order_status', OrderStatusType::class, [
            'expanded' => false,
            'multiple' => false,
            'placeholder' => '選択してください。'
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}
