<?php

namespace Plugin\UKOMI4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\UKOMI4\Entity\Config;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    public function getConfig($name, $default=null)
    {
        $config = $this->findOneBy(['name' => $name]);
        return $config && $config->getValue() ? $config->getValue() : $default;
    }

    public function setConfig($name, $value)
    {
        $config = $this->findOneBy(['name' => $name]);
        if ($config) {
            $config->setValue($value);
        } else {
            $config = new Config();
            $config->setName($name);
            $config->setValue($value);
        }
        $em = $this->getEntityManager();
        $em->persist($config);
        $em->flush($config);

        return $this;
    }
}
